import AuthProvider from '@/components/AuthProvider'
import './globals.css'
import Header from '@/components/shared/Header'
import { DarkModeProvider, useDarkMode } from '@/context/ThemeContext'
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'DEV Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <DarkModeProvider>
      <html lang="en">
        <body className={`bg-gradient-to-b bg-[#DFDFDF] dark:bg-black dark:text-white transition-colors duration-300 min-h-screen ${inter.className}`} suppressHydrationWarning={true}>
          <AuthProvider>
            <Header />
            {children}
          </AuthProvider>
        </body>
      </html>
    </DarkModeProvider>
  )
}
